name: crypto_fetch_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  localization: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_gap: ^1.2.0
  web_socket_channel: ^3.0.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/i18n/
